version: 0.2

phases:
  install:
    runtime-versions:
      ruby: latest
  build:
    commands:
      - .cody/shared/script/install.sh
      - .cody/azurerm/bin/install.sh
      - .cody/azurerm/bin/build.sh
